<?php
header('Content-Type: application/json');
	/*
	$item1 = array(
		"id" => "7",
		"type" => "person", 
		"name"=>"Anne Amuzu", 
		"image" => "https://pbs.twimg.com/profile_images/1692599621/jn__7_of_7__400x400.jpg",
		"twitter" => "Ewoenam",
		"linkedIn" => "",
		"description" => ""
	);

	$item2 = array(
		"id" => "11",
		"type" => "company", 
		"name" => "Nandi Mobile", 
		"image" => "https://pbs.twimg.com/profile_images/1879209071/nandimobile_Logo_400x400.jpg", 
		"twitter" => "nandimobile", 
		"linkedIn" => "",
		"description" => "Infoline service allows local hospitals, churches, NGOs and other businesses to track customer comments, send bulk messages to members using SMS or market specific elements of their organization to potential clients.", 
		"facebook" => "https://www.facebook.com/Nandimobile"
	);
	$item3 = array(
		"id" => "16",
		"type" => "company", 
		"name" => "Meltwater Entrepreneurial School of Technology", 
		"image" => "https://pbs.twimg.com/profile_images/595568237359697920/LAOG2PeI_400x400.png",
		"twitter" => "MESTghana",
		"linkedIn" => "",
		"description" => ""
	);
	$item4 = array(
		"id" => "34",
		"type" => "person", 
		"name" => "Edward Tagoe", 
		"image" => "https://pbs.twimg.com/profile_images/617062478510444544/91yvJhOu_400x400.jpg",
		"twitter" => "ttaaggooee",
		"linkedIn" => "",
		"description" =>""
	);

	$items = array($item1,$item2,$item3,$item4);

	if (isset ($_GET['id'])) {
		$output=array();
		foreach($items as $item) {
			if ($_GET['id'] == $item['id']) {
				$output=$item;
			}
		}
	} else {
		$output=$items;
	}
*/
	?>

	{
	"page_info": {
		"total_accounts": 49,
		"total_pages": 1,
		"first_page": true,
		"last_page": true,
		"previous_page": null,
		"next_page": null,
		"out_of_bounds": false,
		"offset": 0,
		"per_page": 49
	},
	"accounts": [{
		"id": 1,
		"uuid": "13e3a611-b5c8-5bcf-ad9b-b61e932cd9e7",
		"account_type": "Organization",
		"display_name": "Accrascope",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "urban design, environment",
		"keywords": "cities, urban design, urban planning, architecture, design, resiliency, sustainability",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 2,
		"uuid": "df0935fe-0ec1-5219-b440-3763bcb28048",
		"account_type": "Person",
		"display_name": "Anas ",
		"last_name": "Aremeyaw Anas",
		"first_name": "Anas",
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "media, open government",
		"keywords": "journalism, media, investigative journalism, investigative reporting, anti-corruption",
		"url": null,
		"twitter": "@anasglobal",
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 3,
		"uuid": "806774cf-65f5-5c25-9fe8-6af7e7eee56e",
		"account_type": "Person",
		"display_name": "Anne Amuzu",
		"last_name": "Amuzu",
		"first_name": "Anne",
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "entrepreneurs, startups, women in business, women in technology",
		"keywords": "entrepreneurship, startups, mobile, technology",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 4,
		"uuid": "7c3d5ad8-d9be-5b5a-a1e4-1a9505bbaeb6",
		"account_type": "Person",
		"display_name": "Ato Ulzen-Appiah",
		"last_name": "Ulzen-Appiah",
		"first_name": "Ato",
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": null,
		"keywords": null,
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 5,
		"uuid": "e4d87f7e-c1b4-55a6-8de0-123c3a2f78cc",
		"account_type": "Person",
		"display_name": "Ayokunle Ojo",
		"last_name": "Ojo",
		"first_name": "Ayokunle",
		"city_name": "Lagos",
		"country_name": "Nigeria",
		"country_id": 167,
		"categories": null,
		"keywords": null,
		"url": null,
		"twitter": "@ayolope",
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 6,
		"uuid": "e2b4f03a-f280-53a3-aeeb-97abbc113d5b",
		"account_type": "Person",
		"display_name": "Bankole Oluwafemi",
		"last_name": "Oluwafemi",
		"first_name": "Bankole",
		"city_name": null,
		"country_name": "Nigeria",
		"country_id": 167,
		"categories": "technology, media",
		"keywords": "media, technology, startups, ",
		"url": null,
		"twitter": "@MrBankole",
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 7,
		"uuid": "c8100dad-852c-5bc1-bc7f-11d7654607e2",
		"account_type": "Organization",
		"display_name": "Baobab Entrepreneurship",
		"last_name": null,
		"first_name": null,
		"city_name": "Dakar",
		"country_name": "Senegal",
		"country_id": 205,
		"categories": "entrepreneurship, startups, development, innovation",
		"keywords": "entrepreneurship, technology, startups, development, training, workshops",
		"url": null,
		"twitter": null,
		"linkedin": "https://www.linkedin.com/company/baobab-entrepreneurship",
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 8,
		"uuid": "910e8d24-6623-51f4-a480-53c5257c9bd3",
		"account_type": "Organization",
		"display_name": "BarCamp Ghana",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "entrepreneurship, startups, innovation",
		"keywords": "barcamps, entrepreneurship, technology, startups, development, training, workshops",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 9,
		"uuid": "9713da30-19c4-56e5-b4b0-e9552e91b331",
		"account_type": "Person",
		"display_name": "Binyavanga Wainaina",
		"last_name": "Wainaina",
		"first_name": "Binyavanga",
		"city_name": "Nairobi",
		"country_name": "Kenya",
		"country_id": 119,
		"categories": "media, culture",
		"keywords": null,
		"url": null,
		"twitter": "@BinyavangaW",
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 10,
		"uuid": "533104ce-cba1-5577-a3d5-f363debee4ad",
		"account_type": "Organization",
		"display_name": "Breast Care International",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "health",
		"keywords": "healthcare, social good",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 11,
		"uuid": "10653429-96de-53b8-a53c-b0355d401aab",
		"account_type": "Person",
		"display_name": "Chimamanda Adichie",
		"last_name": "Adichie",
		"first_name": "Chimamanda",
		"city_name": "Lagos",
		"country_name": "Nigeria",
		"country_id": 167,
		"categories": "media, authors, culture",
		"keywords": "media, authors, feminism, culture, art",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 12,
		"uuid": "041e9553-9ad6-56c9-947b-aef1f188ad3e",
		"account_type": "Person",
		"display_name": "Chuba Ezekwesili",
		"last_name": "Ezekwesili",
		"first_name": "Chuba",
		"city_name": "Lagos",
		"country_name": "Nigeria",
		"country_id": 167,
		"categories": "economics",
		"keywords": "business, business development, economics, finance",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 13,
		"uuid": "a6b31d29-9860-52cc-b98f-8f1bedef9a6f",
		"account_type": "Organization",
		"display_name": "Co Creation Hub",
		"last_name": null,
		"first_name": null,
		"city_name": "Lagos",
		"country_name": "Nigeria",
		"country_id": 167,
		"categories": "entrepreneurship, startups, development, innovation",
		"keywords": "entrepreneurship, startups, development, innovation, incubators, co working spaces",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 14,
		"uuid": "39a3c760-c20c-5929-9479-edcdb0753372",
		"account_type": "Organization",
		"display_name": "CONCREE",
		"last_name": null,
		"first_name": null,
		"city_name": "Dakar",
		"country_name": "Senegal",
		"country_id": 205,
		"categories": "entrepreneurship, startups, development, innovation",
		"keywords": "entrepreneurship, technology, startups, development, training, workshops",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 15,
		"uuid": "80f71e98-4471-5cdc-80a7-4c62babed26c",
		"account_type": "Organization",
		"display_name": "CTIC",
		"last_name": null,
		"first_name": null,
		"city_name": "Dakar",
		"country_name": "Senegal",
		"country_id": 205,
		"categories": "entrepreneurship, startups, development, innovation",
		"keywords": "entrepreneurship, technology, startups, development, training, workshops",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 16,
		"uuid": "277d21c3-5d7b-595a-94cd-a4b4879fa0af",
		"account_type": "Person",
		"display_name": "David Okwii",
		"last_name": "Okwii",
		"first_name": "David",
		"city_name": "Kampala",
		"country_name": "Uganda",
		"country_id": 245,
		"categories": "media, politics, culture",
		"keywords": null,
		"url": null,
		"twitter": "@OquiDave",
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 17,
		"uuid": "5647912d-9ad9-535c-8e68-27b45008ec0b",
		"account_type": "Person",
		"display_name": "Double F",
		"last_name": "Aguntasolo",
		"first_name": "F",
		"city_name": "Lagos",
		"country_name": "Nigeria",
		"country_id": 167,
		"categories": "media, politics, culture",
		"keywords": null,
		"url": "http://aguntasolo.com/",
		"twitter": "@DoubleEph",
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 18,
		"uuid": "759eaaf0-af90-575d-8815-a50b63ce1995",
		"account_type": "Organization",
		"display_name": "Dynamic Africa",
		"last_name": null,
		"first_name": null,
		"city_name": null,
		"country_name": null,
		"country_id": 1,
		"categories": "art, culture, music, media",
		"keywords": null,
		"url": null,
		"twitter": "@dynamicafrica",
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 19,
		"uuid": "8188fc7f-6c50-5e26-9e8a-7f833b4ad43e",
		"account_type": "Person",
		"display_name": "Elnathan John",
		"last_name": "John",
		"first_name": "Elnathan",
		"city_name": "Abuja",
		"country_name": "Nigeria",
		"country_id": 167,
		"categories": "media, authors, culture",
		"keywords": "media, authors, culture, art",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 20,
		"uuid": "01fad265-441a-5e83-9292-ec7b04551447",
		"account_type": "Organization",
		"display_name": "Environment 360",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "environment, startups, entrepreneurship",
		"keywords": "environment, startups, entrepreneurship, green technology",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 21,
		"uuid": "bc185a39-b73e-51e6-8ac2-ef4964d812da",
		"account_type": "Person",
		"display_name": "Fiifi Biadoo",
		"last_name": "Fiifi",
		"first_name": "Baidoo",
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "entrepreneurship, startups, development, innovation",
		"keywords": "entrepreneurship, startups, development, innovation, incubators, co working spaces",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 22,
		"uuid": "8dd76095-827f-5d10-bcb2-99c93add4edb",
		"account_type": "Organization",
		"display_name": "GhanaThink",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "entrepreneurship, startups, development, innovation",
		"keywords": "entrepreneurship, technology, startups, development, training, workshops",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 23,
		"uuid": "1634a7dd-efb6-51d3-b06d-6cadc3c052ad",
		"account_type": "Person",
		"display_name": "Herbert Acheampong",
		"last_name": "Acheampong",
		"first_name": "Herbert",
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "entrepreneurship, startups, development, innovation",
		"keywords": "entrepreneurship, startups, development, innovation, incubators, co working spaces",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 24,
		"uuid": "dc0a1824-c3fd-5729-963b-2d25080fac8b",
		"account_type": "Organization",
		"display_name": "iDEA",
		"last_name": null,
		"first_name": null,
		"city_name": "Washington, D.C.",
		"country_name": null,
		"country_id": 1,
		"categories": "entrepreneurship, startups, development, innovation",
		"keywords": "entrepreneurship, technology, startups, development, training, workshops",
		"url": "http://www.diasporaalliance.org/about-us/",
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 25,
		"uuid": "60aa216e-c84f-50da-9122-bd12b8ac660b",
		"account_type": "Organization",
		"display_name": "Impact Hub",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "entrepreneurship, startups, development, innovation",
		"keywords": "entrepreneurship, startups, development, innovation, incubators, co working spaces",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 26,
		"uuid": "27680a25-1c8f-573a-9976-47b1b10629e8",
		"account_type": "Organization",
		"display_name": "iSpace",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "entrepreneurship, startups, development, innovation",
		"keywords": "entrepreneurship, startups, development, innovation, incubators, co working spaces",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 27,
		"uuid": "138ceb6e-4cba-5234-886f-b29aa5c22885",
		"account_type": "Person",
		"display_name": "Jemila Abdulai",
		"last_name": "Abdulai ",
		"first_name": "Jemila",
		"city_name": "Abidjan",
		"country_name": "Côte d’Ivoire",
		"country_id": 60,
		"categories": "media, politics, culture, social good",
		"keywords": null,
		"url": null,
		"twitter": "@jabdulai",
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 28,
		"uuid": "27457081-84f0-5562-8adf-1d959dd5dcc2",
		"account_type": "Person",
		"display_name": "Karen Attiah",
		"last_name": "Attiah",
		"first_name": "Karen",
		"city_name": "Washington, D.C.",
		"country_name": null,
		"country_id": 1,
		"categories": "media, politics, art, culture",
		"keywords": null,
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 29,
		"uuid": "acab840b-0a17-5f36-8673-6d2bbe1ece32",
		"account_type": "Organization",
		"display_name": "Ker Thiossane",
		"last_name": null,
		"first_name": null,
		"city_name": "Dakar",
		"country_name": "Senegal",
		"country_id": 205,
		"categories": "technology, design, innovation",
		"keywords": null,
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 30,
		"uuid": "405042f6-6278-5a53-add8-b86aeb80494d",
		"account_type": "Person",
		"display_name": "Kofi Yeboah",
		"last_name": "Yeboah",
		"first_name": "Kofi",
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "entrepreneurship, startups, development, innovation",
		"keywords": null,
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 31,
		"uuid": "4a4fdb98-f2fb-57de-9af6-c5367bb0e321",
		"account_type": "Person",
		"display_name": "Makhtar Ndiaye",
		"last_name": "Ndiaye",
		"first_name": "Makhtar",
		"city_name": "Saint-Louis",
		"country_name": "Dakar",
		"country_id": 0,
		"categories": "media, politics, art, culture",
		"keywords": null,
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 32,
		"uuid": "385d281f-1e0a-5dfb-8ba7-07790f9a8911",
		"account_type": "Organization",
		"display_name": "MESH Ghana",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "entrepreneurship, startups, design, innovation",
		"keywords": "entrepreneurship, startups, design, design thinking, innovation",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 33,
		"uuid": "60fa653b-66cf-5129-adf5-91283f6af84b",
		"account_type": "Organization",
		"display_name": "MEST",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "entrepreneurship, startups, incubators, co working spaces",
		"keywords": "entrepreneurship, startups, development, innovation, incubators, co working spaces",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 34,
		"uuid": "bdf862dc-f990-54ba-b44b-32ad8313fa71",
		"account_type": "Person",
		"display_name": "Modupe Odele",
		"last_name": "Odele",
		"first_name": "Modupe",
		"city_name": "NYC",
		"country_name": "USA",
		"country_id": 0,
		"categories": null,
		"keywords": null,
		"url": null,
		"twitter": "@moeodele",
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 35,
		"uuid": "44ffb182-cec5-5610-aa2d-96a0c94e357a",
		"account_type": "Person",
		"display_name": "Omar Mohammed",
		"last_name": "Mohammed",
		"first_name": "Omar",
		"city_name": null,
		"country_name": null,
		"country_id": 1,
		"categories": "media, journalism",
		"keywords": null,
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 36,
		"uuid": "11c1ee32-24c6-5e58-aa7c-49b5eef27b7f",
		"account_type": "Organization",
		"display_name": "Pen Plus Bytes",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "media, journalism, technology",
		"keywords": "media, journalism, development technology",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 37,
		"uuid": "a526a6aa-6b6b-5a2a-b92b-26cdb31d6eb4",
		"account_type": "Organization",
		"display_name": "Pilolo GH",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "environment, startups, entrepreneurship",
		"keywords": null,
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 38,
		"uuid": "139b2b67-78e2-5076-a4ee-bc85340491ff",
		"account_type": "Person",
		"display_name": "Rahama Wright",
		"last_name": "Wright",
		"first_name": "Rahama",
		"city_name": "Washington, D.C.",
		"country_name": null,
		"country_id": 1,
		"categories": "women in business, entrepreneurship, startups, diaspora",
		"keywords": null,
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 39,
		"uuid": "40773f2d-b78c-50c9-bea5-06c7327163c9",
		"account_type": "Organization",
		"display_name": "Reach for Change",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": null,
		"keywords": null,
		"url": "http://ghana.reachforchange.org/",
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 40,
		"uuid": "773840ac-377c-52fc-b667-e34e6e7f9b0f",
		"account_type": "Person",
		"display_name": "Rotimi",
		"last_name": null,
		"first_name": "Rotimi",
		"city_name": null,
		"country_name": null,
		"country_id": 1,
		"categories": "entertainers, music, art, culture",
		"keywords": "art, culture, music, hip hop, ",
		"url": null,
		"twitter": "@rotimi",
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 41,
		"uuid": "a4bdc228-e2a5-5762-90a7-7467f995cf8b",
		"account_type": "Organization",
		"display_name": "Saint-Louis Blogging Network",
		"last_name": null,
		"first_name": null,
		"city_name": "Saint-Louis",
		"country_name": "Senegal",
		"country_id": 205,
		"categories": "media, journalism, politics",
		"keywords": null,
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": "https://www.facebook.com/groups/248034282064413/?fref=nf",
		"instagram": null,
		"youtube": null
	}, {
		"id": 42,
		"uuid": "c9afe6e1-c390-556d-a836-6c90d018b367",
		"account_type": "Person",
		"display_name": "Sibusiso Tshabalala",
		"last_name": "Tshabalala",
		"first_name": "Sibusiso",
		"city_name": "Cape Town",
		"country_name": "South Africa",
		"country_id": 215,
		"categories": "media, journalism",
		"keywords": "media, journalism",
		"url": null,
		"twitter": "@sbutshabs",
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 43,
		"uuid": "ed515b02-feb8-56fd-bed8-3d8859f65764",
		"account_type": "Person",
		"display_name": "Tayib Fall",
		"last_name": "Fall",
		"first_name": "Tayib",
		"city_name": "Saint-Louis",
		"country_name": "Dakar",
		"country_id": 0,
		"categories": "media, journalism, politics",
		"keywords": null,
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 44,
		"uuid": "d4a4dc59-9181-5c3c-9b57-33ab6b6f0123",
		"account_type": "Person",
		"display_name": "Tolu Ogunlesi",
		"last_name": "Ogunlesi",
		"first_name": "Tolu",
		"city_name": "Abuja",
		"country_name": "Nigeria",
		"country_id": 167,
		"categories": "media, journalism, politics",
		"keywords": null,
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 45,
		"uuid": "822ae109-3b49-57d5-86ae-c456c07e91a1",
		"account_type": "Organization",
		"display_name": "U.S.-Africa Chamber of Commerce",
		"last_name": null,
		"first_name": null,
		"city_name": "Washington, D.C.",
		"country_name": null,
		"country_id": 1,
		"categories": "business development, economics, finance",
		"keywords": "business, business development, economics, finance",
		"url": "https://www.uschamber.com/africa",
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 46,
		"uuid": "83b2b728-eb45-5dff-b10a-1e01465c021f",
		"account_type": "Organization",
		"display_name": "VC 4 Africa",
		"last_name": null,
		"first_name": null,
		"city_name": null,
		"country_name": null,
		"country_id": 1,
		"categories": "business development, economics, finance, innovation, startups, investors",
		"keywords": "business development, economics, finance, innovation, startups, investors",
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 47,
		"uuid": "7bde7ed0-5305-5381-948b-e777cdd89913",
		"account_type": "Organization",
		"display_name": "Volunteering GH",
		"last_name": null,
		"first_name": null,
		"city_name": "Accra",
		"country_name": "Ghana",
		"country_id": 87,
		"categories": "social good",
		"keywords": null,
		"url": null,
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 48,
		"uuid": "53e5c310-6f23-5cf1-84b6-559afef6b63d",
		"account_type": "Organization",
		"display_name": "YAP DC",
		"last_name": null,
		"first_name": null,
		"city_name": "Washington, D.C.",
		"country_name": null,
		"country_id": 1,
		"categories": "business development",
		"keywords": null,
		"url": "http://yapdc.org/",
		"twitter": null,
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}, {
		"id": 49,
		"uuid": "10014027-6bbe-5fd5-8825-7a8f34e0b455",
		"account_type": "Person",
		"display_name": "Yinka Adegoke",
		"last_name": "Adegoke",
		"first_name": "Yinka",
		"city_name": "Lagos",
		"country_name": "Nigeria",
		"country_id": 167,
		"categories": "media, journalism, politics",
		"keywords": null,
		"url": null,
		"twitter": "@yinkawrites",
		"linkedin": null,
		"facebook": null,
		"instagram": null,
		"youtube": null
	}]
}
